-- Este script se provee como referencia estructural para evaluación académica.

CREATE TABLE users (
                       id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                       username VARCHAR(50) UNIQUE NOT NULL,
                       email VARCHAR(100) UNIQUE NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       first_name VARCHAR(100),
                       last_name VARCHAR(100),
                       bio TEXT,
                       colegios VARCHAR(255),
                       estudios VARCHAR(255),
                       trayectoria VARCHAR(255),
                       zonas_marcadas VARCHAR(255),
                       espacio_personal TEXT,
                       foto_perfil VARCHAR(255),
                       last_seen TIMESTAMP,
                       online BOOLEAN DEFAULT false,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       author UUID REFERENCES users(id) ON DELETE CASCADE,
                       content TEXT NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fotos (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id UUID REFERENCES users(id) ON DELETE CASCADE,
                       url VARCHAR(255) NOT NULL,
                       descripcion VARCHAR(255)
);

CREATE TABLE comentarios (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             autor_id UUID REFERENCES users(id) ON DELETE CASCADE,
                             perfil_id UUID REFERENCES users(id) ON DELETE CASCADE,
                             contenido TEXT NOT NULL,
                             fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             leido BOOLEAN DEFAULT false
);

CREATE TABLE likes (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       usuario_id UUID REFERENCES users(id) ON DELETE CASCADE,
                       entidad_id BIGINT NOT NULL,
                       tipo VARCHAR(50) NOT NULL,
                       fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mensajes (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          emisor_id UUID REFERENCES users(id) ON DELETE CASCADE,
                          receptor_id UUID REFERENCES users(id) ON DELETE CASCADE,
                          contenido TEXT NOT NULL,
                          fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          leido BOOLEAN DEFAULT false
);

CREATE TABLE amistades (
                           usuario_id UUID REFERENCES users(id) ON DELETE CASCADE,
                           amigo_id UUID REFERENCES users(id) ON DELETE CASCADE,
                           PRIMARY KEY (usuario_id, amigo_id)
);

CREATE TABLE stories (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         usuario_id UUID REFERENCES users(id) ON DELETE CASCADE,
                         texto VARCHAR(255),
                         imagen_url VARCHAR(255),
                         fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         fecha_expiracion TIMESTAMP NOT NULL
);

CREATE TABLE comentarios_stories (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     usuario_id UUID REFERENCES users(id) ON DELETE CASCADE,
                                     story_id BIGINT REFERENCES stories(id) ON DELETE CASCADE,
                                     contenido TEXT NOT NULL,
                                     fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notificaciones (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                usuario_id UUID REFERENCES users(id) ON DELETE CASCADE,
                                emisor_id UUID REFERENCES users(id) ON DELETE CASCADE,
                                tipo VARCHAR(50) NOT NULL,
                                contenido TEXT,
                                entidad_id BIGINT,
                                leido BOOLEAN DEFAULT false,
                                fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);