spring.datasource.url=jdbc:postgresql://db.ylxpcytucebvzijqyrsx.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Easyjet47Sergio

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true