spring.application.name=thirty-api

# Los datos que acabas de validar en IntelliJ
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.ylxpcytucebvzijqyrsx
spring.datasource.password=Easyjet47Sergio
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci\u00F3n necesaria para Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# El puerto que Render necesita
server.port=${PORT:8080}