spring.datasource.url=jdbc:postgresql://db.ylxpcytucebvzijqyrsx.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Bonfireeasyjet47!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=30000
server.port=${PORT:8080}